version: 2.1
orbs:
  ruby: circleci/ruby@2.1.0


commands:
  run-tests:
    description: Run tests
    steps:
      - run: bundle exec rake test

  run-lint:
    description: Run standardrb lint check
    steps:
      - run: bundle exec rake standard

  run-docs:
    description: Generate docs and update gh-pages
    steps:
      - run: bundle exec rake doc
jobs:
  test:
    parameters:
      ruby_version:
        type: string
      gemfile:
        type: string
    docker:
      - image: 'cimg/ruby:<< parameters.ruby_version >>'
    steps:
      - checkout
      - ruby/install-deps:
          gemfile: <<parameters.gemfile>>
      - run-tests

  lint:
    docker:
      - image: cimg/ruby:2.7
    steps:
      - checkout
      - ruby/install-deps
      - run-lint

  docs:
    docker:
      - image: cimg/ruby:2.7
    steps:
      - checkout
      - ruby/install-deps
      - run-docs

workflows:
  all-tests:
    jobs:
      - lint
      - test:
          matrix:
            parameters:
              ruby_version: ['2.6', '2.7', '3.0', '3.1']
              gemfile:
                [
                  'gemfiles/activesupport_5.2.gemfile',
                  'gemfiles/activesupport_6.0.gemfile',
                  'gemfiles/activesupport_6.1.gemfile',
                  'gemfiles/activesupport_7.0.gemfile',
                ]
            exclude:
              - ruby_version: '2.6'
                gemfile: gemfiles/activesupport_7.0.gemfile
      - docs:
          requires:
            - lint
            - test
          # Disable filter for testing on branch
          # filters:
          #   branches:
          #     only: main
