version: 2.1
orbs:
  ruby: circleci/ruby@2.1.0

executors:
  app-ruby:
    docker:
      - image: cimg/ruby:2.7

commands:
  run-tests:
    description: Run tests
    steps:
      - run: bundle exec rake test

  run-lint:
    description: Run standardrb lint check
    steps:
      - run: bundle exec rake standard

  run-docs-build:
    description: Generate docs
    steps:
      - run: bundle exec rake doc:build

  run-docs-publish:
    description: Update gh-pages
    steps:
      - run: bundle exec rake doc:publish
jobs:
  test:
    executor: app-ruby
    parameters:
      ruby_version:
        type: string
      gemfile:
        type: string
    steps:
      - checkout
      - ruby/install-deps:
          gemfile: <<parameters.gemfile>>
      - run-tests

  lint:
    executor: app-ruby
    steps:
      - checkout
      - ruby/install-deps
      - run-lint

  build-docs:
    executor: app-ruby
    steps:
      - checkout
      - ruby/install-deps
      - run-docs-build
      - persist_to_workspace:
          root: .
          paths: doc

  publish-docs:
    executor: app-ruby
    steps:
      - checkout
      - ruby/install-deps
      - attach_workspace:
          at: ./doc
      - add_ssh_keys:
          fingerprints: # ssh key generated solely for montrose docs
            - "97:43:0c:36:36:1d:83:30:f0:76:d4:9f:d3:71:a8:a5"
      - run:
          name: Configure git
          command: |
            git config user.email "ci-build@rossta.net"
            git config user.name "ci-build"
      - run-docs-publish

workflows:
  all-tests:
    jobs:
      - lint
      - build-docs
      - test:
          matrix:
            parameters:
              ruby_version: ['2.6', '2.7', '3.0', '3.1']
              gemfile:
                [
                  'gemfiles/activesupport_5.2.gemfile',
                  'gemfiles/activesupport_6.0.gemfile',
                  'gemfiles/activesupport_6.1.gemfile',
                  'gemfiles/activesupport_7.0.gemfile',
                ]
            exclude:
              - ruby_version: '2.6'
                gemfile: gemfiles/activesupport_7.0.gemfile
      - publish-docs:
          requires:
            - lint
            - build-docs
            - test
          # Disable filter for testing on branch
          # filters:
          #   branches:
          #     only: main
